---
build_from:
  aarch64: ghcr.io/hassio-addons/base:15.0.9
  amd64: ghcr.io/hassio-addons/base:16.1.3
  armv7: ghcr.io/hassio-addons/base:15.0.9
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
