---
name: MQTT IO
version: dev
slug: mqtt-io
description: Expose GPIO modules and digital sensors via MQTT for remote control and monitoring.
url: https://github.com/hassio-addons/addon-mqtt-io
codenotary: codenotary@frenck.dev
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
homeassistant_api: true
privileged:
  - SYS_RAWIO
map:
  - config:rw
  - share:rw
  - ssl
devices:
  - /dev
options:
  configuration_file: /config/mqtt-io/config.yml
schema:
  configuration_file: str
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
